### ISSUE TITLE
Getting an unauthorized error

### ISSUE THREAD

**Issue by arliber** [ishalyminov/wunderlist2asana#1]
Hi,

Thanks for making this!

I'm getting the following error:

`
asana.error.NoAuthorizationError: No Authorization: Not Authorized
`

I'm sure the token is correct though, I've also tried resetting it..

**Comment by ishalyminov** [comment]
Hi,
Thanks for letting me know!
Just tried to get access to my Asana with the method used here, everything worked. Personal token is of the form "0/12345c2d5a17ca04f50f77c1429cc34b".

If it happens again, could you please attach a stacktrace?

**Comment by arliber** [comment]
Thank you so much, it was my mistake! There are 2 tokens -  and used the wrong one :/
Works perfectly!

**Comment by ishalyminov** [comment]
Cool!
