### ISSUE TITLE
What version of python is needed for this?

### ISSUE THREAD

**Issue by mmynsted** [ishalyminov/wunderlist2asana#2]
I get this error.  

```bash
  File "wunderlist_to_asana.py", line 39
    print u'Processing Wunderlist list "{}" ({}/{})'.format(
                                                   ^
SyntaxError: invalid syntax
```

With python `3.6`.

**Comment by ishalyminov** [comment]
Thanks for letting me know! I only tested it with 2.7

**Comment by mmynsted** [comment]
Oh, my mistake.  Using `2.7` allowed it to work as expected.  Thank you.

**Comment by casegold** [comment]
Just submitted a change to make this Python 3.0 compatible

**Comment by ishalyminov** [comment]
@casegold oh wow, thank you! Could you please make a pull request?

**Comment by casegold** [comment]
@ishalyminov You got it -- my first pull request 👍

**Comment by ishalyminov** [comment]
@casegold awesome, thanks a lot!
