### ISSUE TITLE
Error while trying to execute the second command line

### ISSUE THREAD

**Issue by matthbarbosa** [ishalyminov/wunderlist2asana#5]
Currently, while trying to execute the following line:

`$ python wunderlist_to_asana.py <Wunderlist backup file> <Asana token> <Asana workspace name>`

It will return the following error

> Traceback (most recent call last):
> File "wunderlist_to_asana.py", line 122, in <module>
>     move_content(args.wunderlist_backup, args.asana_token, args.workspace_name)
> File "wunderlist_to_asana.py", line 30, in move_content
>     workspace_id = get_workspace_id(in_asana_token, in_workspace_name)
> File "wunderlist_to_asana.py", line 12, in get_workspace_id
>     for workspace in client.workspaces.find_all()
> File "wunderlist_to_asana.py", line 13, in <listcomp>
>     if workspace['name'] == in_workspace_name
> KeyError: 'id'

The API call does seem to get triggered (on Asana) but no tasks are imported still.

**Comment by ishalyminov** [comment]
Thanks for reporting it! I've updated the code for new Wunderlist/Asana format - please try now.

**Comment by matthbarbosa** [comment]
Wonderful. Everything is working fine now!
