### ISSUE TITLE
[Feature request] Import comments on tasks.

### ISSUE THREAD

**Issue by matthbarbosa** [ishalyminov/wunderlist2asana#6]
I tried on my own but couldn't figure it out.

Can you please implement the option to import the comments (and not just the notes) when moving tasks from Whunderlist to Asana?

Thank you in advance.

**Comment by ishalyminov** [comment]
Hi, Happy New Year!:)

Thanks for trying that out! I've just added the comments support, please check if it works for you.

**Comment by matthbarbosa** [comment]
Happy new year for you too!

And yes, it worked great!

Again, thank you for the amazing support and lightning quick responses!
