### ISSUE TITLE
Make sure you are using Python3

### ISSUE THREAD

**Issue by yabdab** [ishalyminov/wunderlist2asana#8]
Mac still uses Python 2.7, so make sure you upgrade to v.3 of python AND pip

Here is an article that will help:
https://stackoverflow.com/questions/20082935/how-to-install-pip-for-python-3-on-mac-os-x

**Comment by ishalyminov** [comment]
Thanks @yabdab - although I believe the code should work with both Python 2 and 3. Please let me know if it's not the case.

**Comment by yabdab** [comment]
"encoding" is a Python 3 thing I believe. Line 27. I may be wrong though.  ¯\_(ツ)_/¯

**Comment by ishalyminov** [comment]
nice catch! :) fixed using `codecs.open`
